### ISSUE TITLE
Fail to load App Service Explorer with VS Code 1.26.1 and App Service Extension 20190606.16

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1034]
**OS:** All
**Build Version:** [20190606.16](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6612)

**Repro Steps:**
1. Rename a local copy of the VSIX that you installed from *.vsix.zip.
2. Extract the .zip file and find the extension/package.json from it.
3. Find the engines ->vscode value 1.26.0.
4. Find the most closely matched version 1.26.1 form https://code.visualstudio.com/updates
5. Install the extension from VSIX.
6. Restart the vs code and check the result.

**Expect:**
Succeed to load the App Service Explorer.

**Actual:**
Fail to load the App Service Explorer.
![image](https://user-images.githubusercontent.com/34729092/59024188-f1c7b080-8883-11e9-9b89-2b589502be85.png)

**Comment by nturinski** [comment]
Hi @v-dantch 

I think that this is actually being caused by the Azure Account extension as I can run the current App Service build on 1.26.1

![image](https://user-images.githubusercontent.com/5290572/59068289-a227bb80-8868-11e9-89ed-b8d026735f37.png)

When you try to run the Azure App Service extension on the older version, you have to uninstall the most recent Azure Account extension (and also uninstall App Service since it relies on it).  Then on vscode 1.26.1, reinstall Account and App Service.  It'll install Azure Account v0.4.3 and App Service should then work.

**Comment by v-dantch** [comment]
Hi @nturinski   yes , you are also correct👏. I ignore the version of Azure Account 😔.
Really thanks for your patience and I will be introspective as well.

**Comment by nturinski** [comment]
@v-dantch No worries!  You do so much good work, you wouldn't be human if you didn't make a mistake every once and a while 😄

**Comment by v-dantch** [comment]
Hi Nathan, you are really NICE and UNDERSTANDING😉.
