### ISSUE TITLE
Region norwayeast is unsupported in VS Code create webapp

### ISSUE THREAD

**Issue by baardl** [microsoft/vscode-azureappservice#1394]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: BadRequest
Error Message: Unsupported location: norwayeast

Version: 0.16.2
OS: linux
OS Release: 5.3.0-29-generic
Product: Visual Studio Code
Product Version: 1.42.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:877989
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
If you try to create Norwayeast from the portal, it will throw this error:

`This region is marked closed for Azure Internal subscriptions due to hardware capacity constraints. Try selecting different region or scale option. Please email AntCapLoop@microsoft.com for more information.`

We should see if there's a way to detect this before hand or at least throw a more useful error.

**Comment by EricJizbaMSFT** [comment]
Just to clarify - are you normally able to create a web app in norwayeast? Does it work in the portal?
