### ISSUE TITLE
Can not create a Node.js Web App in Azure

### ISSUE THREAD

**Issue by laitinenp** [microsoft/vscode-azureappservice#1495]
Hi,

I have been trying to create a Node.js web application according to this documentation [ https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs ]. Stopped after step 7 saying something about the linux server farm (the actual message disappeared).

I am using the SmartICT subscription.

Best Regards,
Petri Laitinen, petri.laitinen@karelia.fi

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: BadRequest
Error Message: Exceeded the limit of 1 free tier linux server farm per subscription.

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3677746extension.bundle.js:225:3677746
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:582086
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:200:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @laitinenp

Thanks for reporting!  It looks like the error message was `Exceeded the limit of 1 free tier linux server farm per subscription.`.  I believe that you may already have a Linux app service plan on this subscription.

If you want to use that app service plan, you can right-click your subscription and select `Create Web App (Advanced)...`  to select your existing plan.  Otherwise, you can delete your old web app and the plan with it, and then proceed normally.
