### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by tiagornandrade** [microsoft/vscode-azureappservice#1499]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "mandakaru" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: pt-br

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3758739
extension.bundle.js:225:3756603extension.bundle.js:225:3756603
i extension.bundle.js:225:3756289
extension.bundle.js:225:3758462extension.bundle.js:225:3758462
t.ExtHostProgress._withProgress extensionHostProcess.js:544:963
t.ExtHostProgress.withProgress extensionHostProcess.js:544:717
Object.withProgress extensionHostProcess.js:867:255
Object.<anonymous> extension.bundle.js:225:3758394
fulfilled extension.bundle.js:225:3756357
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @tiagornandrade 

Looks like your web app is connected to a GitHub repo.  As the error message indicates, in order to deploy to your web app, you should just push your recent changes to whatever repository your app is linked with.

If you want to deploy via another method, right-click the app and click `Configure Deployment Source...`
