### ISSUE TITLE
A warning notification pops up after deploying node.js project to Linux web app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1533]
**OS:** Mac & Win10
**Build:** [20200511.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19056&view=results)

**Repro Steps:**
1. Open the nodejs-docs-hello-world-master project folder in VS Code.
2. Deploy it to a Linux Web App.
3. Wait a minute after deploying successfully.
4. Check the result.

**Expect:**
There is no warning.

**Actual:**
A warning notification "A critical error: tar (child): node_modules.tar.gz: Cannot open: No such file or directory" pops up.
![image](https://user-images.githubusercontent.com/57662131/81659309-2c5ea380-946c-11ea-8749-c9548bbc4e86.png)

**More Info:**
1. This issue doesn't reproduce on Windows Web App.
2. This issue doesn't reproduce on Python and C# projects.

**Comment by nturinski** [comment]
Hi @v-xinda

That message is a new feature added back in 04/27/2020.  Clicking on "View details" should show you a page with more detailed log information.

Currently this feature only works for Linux (maybe only Node) apps.

If you browse to that website, it should have an error since it seems like it didn't deploy correctly.
