### ISSUE TITLE
Unable to verify the first certificate.

### ISSUE THREAD

**Issue by gerh87** [microsoft/vscode-azureappservice#1563]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: UNABLE_TO_VERIFY_LEAF_SIGNATURE
Error Message: unable to verify the first certificate

Version: 0.16.5
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1317:34
TLSSocket.emit events.js:203:13
TLSSocket._finishInit _tls_wrap.js:792:8
TLSWrap.ssl.onhandshakedone _tls_wrap.js:606:12
```

</details>

**Comment by gerh87** [comment]
We are trying to deploy our application to azure with this complement from VS code but, we are getting this error. Please someone could help us?

**Comment by nturinski** [comment]
Hi @gerh87

Thanks for reporting.  Sorry that you're having problems deploying.  Have you been able to deploy with any other methods?  I don't know if it's due to your project's configurations or something that VS Code is doing that's causing this issue.

According to [this post](https://stackoverflow.com/questions/17200391/nodejs-unable-to-verify-leaf-signature/50211043), you may be able to change your SSL settings for your project.  Let me know if that resolves anything!

**Comment by nturinski** [comment]
There's also this: https://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature
