### ISSUE TITLE
[Suggestion] Add the commands for Trial App in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1642]
**OS:** Win10
**Build Version:** 20200701.1

**Repro Steps:**
1. Right click one Trial App and check the context menu.
![image](https://user-images.githubusercontent.com/45614674/86221237-3b81e800-bbb7-11ea-8183-a50bed3c98a9.png)
2. F1 to check the command list.

**Actual:**
There is no command for Trial App.

**Suggestion:**
Add the commands for Trial App in command palette.

**Comment by alexweininger** [comment]
We are leaving the Trial app commands out of the command palette because we don't want the Trial app commands to clutter the palette with very similar looking commands for Trial apps that are normally for real web apps.

Going to wait to close this however because it would be great if we could dynamically add Trial app commands to the palette if we detect the user has a Trial app.

**Comment by EricJizbaMSFT** [comment]
> because it would be great if we could dynamically add Trial app commands to the palette if we detect the user has a Trial app.

I'm not sure it's worth it, but it's definitely possible. For example, the Docker extension dynamically hides some Azure-specific stuff

You use the "setContext" command to change a value (i.e. 'isAzureAccountInstalled'):
https://github.com/microsoft/vscode-azuretools/blob/master/ui/src/treeDataProvider/AzureAccountTreeItemBase.ts#L195

And then you check that value in a "when" clause in package.json:
https://github.com/microsoft/vscode-docker/blob/0ec9fcbe7b2248792b03e9d658012e7c232bf99c/package.json#L459

**Comment by EricJizbaMSFT** [comment]
Boss man Jing wants it
