### ISSUE TITLE
There is an error when entering fewer than 59 characters for create a new deployment slot

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1659]
**OS:** All
**Build Version:** 20200703.6
Does this occur consistently? Yes

**Repro steps:**
Create a new deployment slot --> Enter a name with 43 characters.

**Expect:**
There is no error.

**Actual:**
There is an error when entering the 43rd character on Windows.
![image](https://user-images.githubusercontent.com/62053665/86568617-b7a57280-bf9f-11ea-8e97-7e0468577c37.png)

**More info:**
This issue reproduce when  entering the 45rd character on Mac.
This issue reproduce when  entering the 41rd character on Linux.

**Comment by EricJizbaMSFT** [comment]
@v-mengwe how long is the site name? As the message says, the site name and slot name _combined_ have to be fewer than 59 characters.

**Comment by v-mengwe** [comment]
@EricJizbaMSFT Thanks for your guidance.
The length of the site name depends on the length of the Web App name, it between 2 and 60 characters.
![image](https://user-images.githubusercontent.com/62053665/86691322-4ca97980-c03b-11ea-8354-f1a67890735e.png)
The length of the slot name must be at least 2 characters.
![image](https://user-images.githubusercontent.com/62053665/86691512-75ca0a00-c03b-11ea-8152-3525d0d2f659.png)
As the message says, if the site name exceeds 57 characters(does not contain 57 characters), the slot name will can't be create. So, is it possible to balance the length of the site name and slot name?

**Comment by EricJizbaMSFT** [comment]
> So, is it possible to balance the length of the site name and slot name?

What do you mean by this?

**Comment by v-mengwe** [comment]
As the message says, the site name and slot name combined have to be fewer than 59 characters. But, the maximum length of the site name alone is already greater than their sum. So, is it possible to adjust their length? For example, shorten the length of the site name, or increase the length of the slot name.

**Comment by EricJizbaMSFT** [comment]
@v-mengwe these limits are set by the platform and we can't change them. That being said, I'll explain a bit why the platform has these limits. If I have a site named "site1", it's url will look like "site1.azurewebsites.net". If I have a slot named "slot1" on that site, it's url will look like "site1-slot1.azurewebsites.net". The part of the url before ".azurewebsites.net" has to be 60 characters or less (I think that's just how urls work or something 🤷‍♂️). In the slot case, you'll notice there's a hyphen between the site name and slot name, taking up 1 character - that's why we have a combined limit of 59 instead of 60 in that case.

**Comment by v-mengwe** [comment]
Got it. Thanks a lot for your update.
