### ISSUE TITLE
Trial app create experience is different depending on browser and authentication method

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureappservice#1672]
Using this link https://code.visualstudio.com/tryappservice/ in Chrome, authenticating with GitHub or captcha takes you here:
<img width="798" alt="Screen Shot 2020-07-06 at 12 24 36 PM" src="https://user-images.githubusercontent.com/22795803/86632012-b6fee300-bf83-11ea-981f-f0a4815f2da1.png">

Authenticating with Microsoft takes you here:
<img width="1045" alt="Screen Shot 2020-07-06 at 12 33 21 PM" src="https://user-images.githubusercontent.com/22795803/86632977-ed892d80-bf84-11ea-98fd-04db33dab631.png">

Same behavior in Safari, except authenticating with Captcha takes you to https://code.visualstudio.com 😭

**Comment by fashaikh** [comment]
This happens when you try a different auth method after you already have one resource in the same browser session (different tab or same) . Likely because the browser sends the previously cached session information. There was some discussion around this earlier, cant find the issue. Created a new one to track this for future. 
https://github.com/projectkudu/TryAppService/issues/95

**Workaround**: use a different browser in this case or close al inPrivate sessions and open a new one

**Comment by ejizba** [comment]
Closing because of https://github.com/microsoft/vscode-azureappservice/issues/1880
