### ISSUE TITLE
Azure wont push to my git repo

### ISSUE THREAD

**Issue by marwan69** [microsoft/vscode-azureappservice#1714]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "TOKEN-CREATOR" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.18.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3757968
extension.bundle.js:225:3755824
i extension.bundle.js:225:3755510
extension.bundle.js:225:3757682
t.ExtHostProgress._withProgress extensionHostProcess.js:578:963
t.ExtHostProgress.withProgress extensionHostProcess.js:578:717
Object.withProgress extensionHostProcess.js:918:395
Object.<anonymous> extension.bundle.js:225:3757614
fulfilled extension.bundle.js:225:3755578
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @marwan69

Thank you for using the extension!  In order to deploy to Azure, you will need to push to your GitHub repository, not to the app service.  Once you push a change to your repo, the changes will automatically be picked up by your web app.

If that doesn't resolve your issue, please let me know.
