### ISSUE TITLE
VSCode Node Azure Deployment: EPIPE Error

### ISSUE THREAD

**Issue by DiegoHuesos** [microsoft/vscode-azureappservice#1810]
Does this occur consistently? 
YES
Repro steps:

1. Deploy Project From VSCode 

Action: appService.Deploy
Error type: EPIPE
Error Message: write EPIPE

Version: 0.19.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:87:16
```

</details>

**Comment by nturinski** [comment]
Hi @DiegoHuesos,

I'm sorry that you are having issues with deploying. Has this issue been reproducible? An EPIPE error happens when one end of the connection is closed. Maybe there was an outage at the time you tried to deploy? If this is not the case, could you answer the following question?

1. Was this a new web app?
1. Is this a Linux or Windows app?
1. What type of project are you trying to deploy?

Thank you!
