### ISSUE TITLE
Node app won't deploy - says another deployment is in progress

### ISSUE THREAD

**Issue by athelene** [microsoft/vscode-azureappservice#1951]
Does this occur consistently?  YES
Repro steps:

1. Use the Deploy button in Visual Studio Code
2. Note: I used the deploy button and it failed. Tried again and it just hung up. Restarted the app from Visual Studio Code and tried again. Same result. Stopped and started the service from the Azure portal and tried again with the same result. 
3. I am ONLY trying to deploy the sample app per following the instructions in the quick start.  There's nothing special. All the Quick Start instructions worked perfectly up until the deploy. (https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?pivots=platform-windows)

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.53.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by athelene** [comment]
I noticed a note at the side of this issue that suggested I could merge a pull request to close the issue. I did that. Now I'm able to run the deploy. However, it fails with a message: Could not detect any platform in the source directory. Error: Couldn't detect a version for the platform 'nodejs' in the repo.

Given that I'm using the steps in the Quick Start, I'm kind of stumped as to what may be missing or wrong.

**Comment by athelene** [comment]
I decided to explore the Deployment Center. Added a local GIT source there. Now when I try to deploy I get the following error: 

2:00:35 PM: Error: fatal: the remote end hung up unexpectedly
error: error in sideband demultiplexer

Not sure if this is helpful or not but does seem to indicate that something is not responding on the server side?

**Comment by ejizba** [comment]
You've mentioned several issues here, but I'm just going to focus on the original comment for the sake of simplicity. I'm not familiar with the "note at the side of this issue" you mentioned and I would not recommend "local git" if you're just getting started.

The error message "There is a deployment currently in progress" happens when you try to deploy multiple times in a row. Unfortunately, there are rare cases where the Web App in Azure gets stuck with this message even after the old deployment finishes. We don't have a fix for this (Tracking in https://github.com/microsoft/vscode-azureappservice/issues/1589), but people usually report success if they just delete that web app and re-create a new one. If you don't want to do that, my only other recommendation is to contact Azure support
