### ISSUE TITLE
Using Azure App Service for long periods of time causes "Entry not found in cache"

### ISSUE THREAD

**Issue by freeone3000** [microsoft/vscode-azureappservice#1963]
Does this occur consistently? Yes
Repro steps:

1. Have Azure panel open for an hour or two
2. Attempt to deploy service
When the local cache is expired, I expect the plugin to automatically refresh from the cache, instead of giving an error.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: win32
OS Release: 10.0.21301
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:76673extension.js:243:76673
extension.js:243:74654extension.js:243:74654
extension.js:243:74274extension.js:243:74274
i.find extension.js:243:108806
extension.js:243:53535extension.js:243:53535
```

</details>

**Comment by nturinski** [comment]
As you suspect, leaving your Azure panel inactive for a while will typically cause this bug.

This is usually caused by another bug being tracked upstream here: microsoft/vscode-azure-account#53 that's unfortunately out of our control.

As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.
