### ISSUE TITLE
Unable to create a web app using vs code aand azure extension.

### ISSUE THREAD

**Issue by MohdMaaz19** [microsoft/vscode-azureappservice#1965]
Does this occur consistently? 
Repro steps:

1.Tried craeting an app using the VS Code Azure extension but was greeted with this error.

Action: appService.CreateWebApp
Error type: Conflict
Error Message: Server Farm with name 'appsvc_linux_centralus' already exists for subscription '5588708f-9f99-4c4c-b379-cbb672ee4c81'.

I have deleted the any previous instances of 'appsvc_linux_centralus'.

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
@MohdMaaz19 Weird, have you created a web app with the extension prior to getting this error?  Where did you delete `appsvc_linux_centralus`?  How long ago was it?  It might be some race condition where the app service plan is deleted, but not fully yet.

A workaround for now would be to use advanced create so that you can specify what app service plan to use.
