### ISSUE TITLE
Error 403 - This web app is stopped. 

### ISSUE THREAD

**Issue by RomanSebranek** [microsoft/vscode-azureappservice#2003]
Hi Guys,

deploying to my azure web app docfx project by this way:
<img width="294" alt="Snímek obrazovky 2021-03-18 v 10 10 17" src="https://user-images.githubusercontent.com/39954078/111601178-67d7a600-87d2-11eb-9e58-a13ee3509043.png">

Output retrieves following error state:
Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the web app administrator, please find the common 403 error scenarios and resolution here [https://go.microsoft.com/fwlink/?linkid=2095007]. For further troubleshooting tools and recommendations, please visit Azure Portal [https://portal.azure.com/].

Web app is up and running:
<img width="455" alt="Snímek obrazovky 2021-03-18 v 10 15 16" src="https://user-images.githubusercontent.com/39954078/111601804-049a4380-87d3-11eb-9078-2f875a2b3889.png">

can someone help, please? 
Thanks!

**Comment by nturinski** [comment]
Hi @RomanSebranek  I've been looking [online](http://thewindowsupdate.com/2019/04/01/azure-web-apps-error-403-this-web-app-is-stopped-2/), and it seems like a common reason for this error is your app service plan is running into quota issues.  Do you happen to be using a free tier?  

You might be able to circumvent this by trying to create another free app service plan and deploying to a new app.  If you are using Linux, you may have to delete your old free plan first though.

**Comment by RomanSebranek** [comment]
Hi @nturinski I really appreciate your reaction, the application runs in standard app service plan (S1: 1). 
I have also read these articles completely.
Don't you have any other idea?
Thnx!

**Comment by nturinski** [comment]
I'm sorry @RomanSebranek.  Unfortunately, outside of making a new web app or trying to deploy with the CLI, I don't really have any great suggestions.  Since we're only the tooling team, we have a hard time troubleshooting problems with the service outside of things that we see commonly.

You should be able to make a support ticket in the portal though.  If you click on your app, there should be a Support + troubleshooting section.  Then click `New Support Request`.  Sorry that I can't offer more assistance.
![image](https://user-images.githubusercontent.com/5290572/112220076-13259800-8be3-11eb-8154-eb1d097dcd4c.png)
