### ISSUE TITLE
Deployment - Connect GitHub repository is empty on Choose organization

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azureappservice#2046]
I have a github repo that I've forked so both my origin and remote have values. 

```
origin  https://github.com/diberry/js-e2e-express-server.git (fetch)
origin  https://github.com/diberry/js-e2e-express-server.git (push)
upstream        https://github.com/Azure-Samples/js-e2e-express-server.git (fetch)
upstream        https://github.com/Azure-Samples/js-e2e-express-server.git (push)
```

In VS Code for the app service, which I've already deployed once and ran locally so the code runs in both places. I selected the Azure app service then selected **Deployments** then selected **Connect to a GitHub Repository**. The 1/3 form item is empty for **Choose organization**. 

![image](https://user-images.githubusercontent.com/41597107/118188534-6357f400-b3f5-11eb-8955-a708146681a0.png)

If I enter my fork name, 'diberry', as the value, the entire tab closes.

**Comment by ejizba** [comment]
Yeah we don't check your local remotes at all for this, so that's probably unrelated. I think we ask you to connect your Azure account to GitHub and we use that login to list the organizations. @diberry does that sound familiar - and did you set up the right account? It probably would've pointed you to the Azure portal in the browser to do that

@nturinski for any other ideas as he authored this flow

**Comment by nturinski** [comment]
Hi @diberry

Everything that @ejizba said is correct.

The GitHub experience for App Service relies on a source token that we are getting from Azure.  If you check this link https://github.com/settings/applications, you should see Azure App Service being authorized.

![image](https://user-images.githubusercontent.com/5290572/118712376-932c4080-b7d5-11eb-94c6-6ec09b8a8137.png)

If you don't see this app being authorized in your settings, it's possible that a different GitHub account was authorized.  Otherwise, your GitHub username and all of your orgs should be displayed at the step shown in your screenshot.  There could be something glitched in Azure in which case, you can try revoking access and going through the authentication process again.
