### ISSUE TITLE
Investigate ECONNRESET issue during "zipdeploy" call

### ISSUE THREAD

**Issue by 76grady** [microsoft/vscode-azureappservice#2082]
**Steps to reproduce**

I'm attempting to deploy an Angular app to an app service using VS Code.  If I do a few concurrent deploys of the same application to different slots it will happen.  It's happening both on both Mac and Windows machines. 

I will switch to another machine and it will work for a number of times, and then the same behavior will happen again. 

**Current behavior**

`12:37:09 PM <app service name>: Starting deployment...`
`12:37:16 PM <app service name>: Creating zip package...`
`12:42:38 PM: Error: request to <app service domain>/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET`

**Expected behavior** 

The app deploys

**Environment stuff**

On Mac
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z (1 day ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Windows 
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z (1 day ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by ejizba** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2844

**Comment by ejizba** [comment]
Yeah we are aware of occasional ECONNRESET errors, but do not have a fix yet. We will look into it

**Comment by 76grady** [comment]
@ejizba are there any workarounds for this issue?  Any caches to clean or settings to reset?  I literally cannot deploy via VS Code on any of my machines.

**Comment by ejizba** [comment]
We've struggled to get a consistent repro - the main workaround is just to try again and normally it works. If you can help us get a consistent repro that would be much appreciated. Some questions:

1. Would you say your internet is particularly slow?
2. Is your project particularly large?
3. Are you behind a proxy of any kind?
4. Is your project open source, like on GitHub? If so, could we get a link?
5. What kind of app and plan are you using in Azure? For example, is it a basic plan and does it have a lot of apps associated with it? Is it windows or linux?
5. Does this repro for you on a brand new app when deploying a simple project?

The main point is I'm trying to narrow down if the issue is related to your local project, your app in Azure, or your local machine setup.
