### ISSUE TITLE
The "Hello World" doesn't show in the webpage after browsing website of a Nodejs web app's slot

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2110]
**OS:** Linux/Mac
**Build Version:** 20210805.11

**Repro Steps:**

1. Create a Windows Nodejs web app -> Create a slot to it.
2. Deploy the Nodejs project to the slot.
3. Browse the website.
4. Check whether the "Hello World" shows in the webpage.

**Expect:**
The "Hello World" shows in the webpage.

**Actual:**
The "Hello World" doesn't show in the webpage.
![image](https://user-images.githubusercontent.com/57662131/128487910-6cd1adbf-dde3-463a-84fe-1ddb44d6b5ef.png)

**More Info:**
1. This issue doesn't reproduce for Windows Nodejs web app.
2. This issue doesn't reproduce on Windows.

**Comment by ejizba** [comment]
What did you choose for this prompt?
<img width="368" alt="Screen Shot 2021-08-06 at 9 38 46 AM" src="https://user-images.githubusercontent.com/11282622/128543470-fc9640e4-51bf-4664-a318-90f26d23aecb.png">

I can repro if I select "Don't clone" because then it's missing the `WEBSITE_NODE_DEFAULT_VERSION` app setting, which is required for windows node.js apps to work. If I manually add the setting, it starts working again for me. It also works just fine if I clone from an existing slot.

**Comment by v-xinda** [comment]
@ejizba I choose the "Don't clone configuration..." for the above prompt when creating one slot.

**Comment by ejizba** [comment]
We don't think this happens very often and there's an existing workaround, so we're going to close as 'wont-fix'
