### ISSUE TITLE
The deployment source isn't swapped between the production and slot after swapping

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2163]
**OS:** Win10
**Build Version:** 20211221.1
**Regression:** Not a regression

**Repro Steps:**

1. Create a Node Linux web app -> Create a slot for it -> Deploy a nodejs-docs-hello-world-master project to it. (The deployment source is `None`)
2. Open up the 'Deployments' node and select 'Connect to Github…' of Node Linux web app -> Select a Github org -> Select "node-todo" -> Select "master". (The deployment source is `GitHub`)
3. Expand the connections node of Node Linux web app -> Install Database extension -> Add a MongoDB account connection to web app.
4. Swap the slot with production.
5. Check whether the deployment source is swapped between the production and slot.

**Expect:**
The deployment source is swapped between the production and slot.

**Actual:**
The deployment source isn't swapped between the production and slot.
![image](https://user-images.githubusercontent.com/62053665/147229347-1796a0aa-ff31-4ed9-a1f2-a861b4eafe78.png)

**More Info:**

1. The Database is swapped between the production and slot.
2. The webpage is swapped between the production and slot.

**Comment by nturinski** [comment]
I'm not sure that the deployment source is supposed to be swapped or not.  If you look at this list of settings that aren't swapped, publishing endpoint is one of them: https://scontent-sea1-1.xx.fbcdn.net/v/t1.18169-9/1524946_10151907235762545_1003321836_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=a9b1d2&_nc_ohc=tQx-hp-aRecAX8hfCTV&_nc_ht=scontent-sea1-1.xx&oh=00_AT9WD3d7vYSEdAnDEdTa2Rdt8Byrzb6FWSk0VXH6uZJzgQ&oe=61FE7E82

I'm not sure if publishing endpoint is the same thing as the deployment source, but I suspect that it's intentional that it's not swapped between production and the slot.

**Comment by nturinski** [comment]
Closing due to the fact that deployment source is not on the list of settings to be swapped in documentation so I assume that this is intentional.
