### ISSUE TITLE
There are 2 "Refresh/Open in Portal/View Properties" actions in the web app context menu

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2224]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Service Extension Build Version:** 20220421.6 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Right click a web app to open its context menu.
2. Check whether there is only one "Refresh" action or not.

**Expect:**
There is only one "Refresh" action in the web app context menu.

**Actual:**
There are 2 "Refresh" actions in the web app context menu.
<img width="340" alt="Screen Shot 2022-04-24 at 15 41 20" src="https://user-images.githubusercontent.com/62053665/164966511-3bda5aaf-e3d9-4187-9ee1-6a62e673f79e.png">

**More Info:**
There are 2 "Open in Portal" and "View Properties" in the web app context menu.

**Comment by alexweininger** [comment]
This is mostly fixed by https://github.com/microsoft/vscode-azureappservice/pull/2232, however App Service has a custom async view properties command which is different from the default contributed by RGs. Not sure how we want to solve this.

![image](https://user-images.githubusercontent.com/12476526/165389329-ca9b0062-62bd-4b20-a316-97471fc03bf6.png)

**Comment by alexweininger** [comment]
Closed by #2237
