### ISSUE TITLE
The file changes if select "Don't upload" when saving it

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2302]
**OS:** Win 10
**Build:** 20220803.1
**Regression:** Not a regression

**Repro Steps:**

1. Expand a web app -> Expand the "Files" node -> Open the hostingstart.html file -> Edit the file and make changes -> Ctrl + S -> Select "Don't upload" -> Close the file -> Reopen this file.
2.  Check whether the file doesn't change.

**Expect:**
The file doesn't change.

**Actual:**
The file changes.

**More Info:**
1. If click circle icon to close the file and select "Don't save", the file doesn't change after reopening it.
2. Refresh can fix this issue.

**Comment by nturinski** [comment]
This is happening because while the file isn't getting uploaded, it is being saved locally.  We don't re-poll the data every time we open the file, so we probably just save the contents directly to the tree node.

The refresh is fixing it because it is recreating the files node from data it is getting from Azure, so it is reverted back to what it originally was.

This bug seems pretty edge-case and low-risk unlikely to happen to most users so I'll close this as `wontfix` unless we have customer feedback indicating that we should resolve this issue.
