### ISSUE TITLE
Could not publish a simple node.js app

### ISSUE THREAD

**Issue by tanzle-aames** [microsoft/vscode-azureappservice#2332]
This is the output when attempting to publish a simply test node.js app:

6:24:44 AM MyTestApp: Starting deployment...
6:24:44 AM MyTestApp: Creating zip package...
6:27:24 AM MyTestApp: Zip package size: 47.7 MB
6:27:29 AM MyTestApp: Fetching changes.
6:27:29 AM MyTestApp: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/65f48eb1-e944-430f-944a-10118ca761b1.zip (45.15 MB) to /tmp/zipdeploy/extracted
6:27:29 AM MyTestApp: Offset to Central Directory cannot be held in an Int64.
6:27:35 AM MyTestApp: Deployment failed.

**Comment by nturinski** [comment]
It seems like this issue can happen randomly. Based off [this](https://stackoverflow.com/questions/34423322/offset-to-central-directory-cannot-be-held-in-an-int64) and [this](https://github.com/projectkudu/kudu/issues/3348) issue, it seems like it has something to do with the zipping. We've changed the way we've zipped our files since then, so maybe this issue has gone away?

I know its over 2 years old, but if @tanzle-aames could confirm, that would be awesome!
