### ISSUE TITLE
Remote Debugging - Unable to establish connection to application: App is started, but port is unreachable

### ISSUE THREAD

**Issue by nileriver23** [microsoft/vscode-azureappservice#2366]
When I try to start a remote debugging session I get the following message: 

"Unable to establish connection to application: App is started, but port is unreachable"

I have a Python on Linux application. I do have VNET integration enabled for outbound traffic. Also, I am able to remote SSH.

**Comment by nturinski** [comment]
Could you check in the Azure Portal to see if remote debugging is enabled?  We're supposed to do it when we start remote debugging, but I think we may not be successfully changing the port to allow remote debugging.

![image](https://user-images.githubusercontent.com/5290572/217678903-693dcb6e-0d5a-445d-9de1-05d3e209d1e7.png)
![image](https://user-images.githubusercontent.com/5290572/217678966-2def14e9-8846-48ce-bdd1-bb012bc9a8b3.png)

**Comment by nileriver23** [comment]
I can confirm that it is turned on.

**Comment by nileriver23** [comment]
Also, I was able to get it to work using a Flask application. Am still not able to get it to work with my application built using the Pyramid framework. Is that to be expected?

**Comment by nturinski** [comment]
I'm sorry, but I'm not sure exactly which frameworks it supports. My knowledge of the constraints of remote debugging is really limited because we just enable it within our tools, but we didn't actually work on the implementation.

There is a learn guide about Python debugging [here](https://learn.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines?view=vs-2022) that might be helpful.
