### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by AwaabElamin** [microsoft/vscode-azureappservice#2416]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Redeploy
Error type: Error
Error Message: Redeploy is not supported for non-git deployments.

Version: 0.24.7
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.0
Language: en

<details>
<summary>Call Stack</summary>

```
DeploymentTreeItem.<anonymous> extension.bundle.js:2:2474947
extension.bundle.js:2:2473445extension.bundle.js:2:2473445
S extension.bundle.js:2:2473131
DeploymentTreeItem.redeployDeployment extension.bundle.js:2:2474874
extension.bundle.js:2:3796856extension.bundle.js:2:3796856
extension.bundle.js:2:3796441extension.bundle.js:2:3796441
S extension.bundle.js:2:3796127
redeployDeployment extension.bundle.js:2:3796629
extension.bundle.js:2:2667327extension.bundle.js:2:2667327
fulfilled extension.bundle.js:2:2666601
```

</details>

**Comment by alexweininger** [comment]
What deployments source is your web app using? 

From the error message, your web app is currently configured with continuous deployment. [More info](https://learn.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment?tabs=github)

You can change the deployment source in the extension like so:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/12476526/225770013-cd0c1c24-f1e6-4d86-b08b-08d96df9d374.png">

In order to deploy directly from our extension change the deployments source to "None". 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/12476526/225770075-8b2fa324-7d5f-40f5-9112-1361abc05a19.png">
