### ISSUE TITLE
//

### ISSUE THREAD

**Issue by AwaabElamin** [microsoft/vscode-azureappservice#2418]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "AwaabAzureAngular" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.24.7
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410350
extension.bundle.js:2:2408199extension.bundle.js:2:2408199
S extension.bundle.js:2:2407885
extension.bundle.js:2:2410000extension.bundle.js:2:2410000
y.d extensionHostProcess.js:96:43826
y.withProgress extensionHostProcess.js:96:43669
Object.withProgress extensionHostProcess.js:117:41056
Object.<anonymous> extension.bundle.js:2:2409931
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by alexweininger** [comment]
From the error message, your web app is currently configured with continuous deployment. [More info](https://learn.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment?tabs=github)

You can change the deployment source in the extension like so:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/12476526/225770013-cd0c1c24-f1e6-4d86-b08b-08d96df9d374.png">

In order to deploy directly from our extension change the deployments source to "None". 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/12476526/225770075-8b2fa324-7d5f-40f5-9112-1361abc05a19.png">
