### ISSUE TITLE
Fail to deploy the project by clicking "Deploy" button from the notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2421]
**OS:** Windows 10
**Build Version:** 20230314.4

**Repro Steps:**
1. Open "[nodejs-docs-hello-world](https://github.com/Azure-Samples/nodejs-docs-hello-world/archive/master.zip)" project in VS Code.
2. Create a Node web app.
3. Click "Deploy" button from the below notification -> Select the project to deploy.
![image](https://user-images.githubusercontent.com/45614674/225232974-b69f0c60-3e16-43f8-bb87-5926ca43adf7.png)
4. Check whether succeeds to deploy the project or not.

**Expect:**
Succeed to deploy the project.

**Actual:**
Fail to deploy the project with an error.
![image](https://user-images.githubusercontent.com/45614674/225233312-3b57e73d-2ec5-47bf-8b06-a21442c851ef.png)

**More Info:**
This issue does not reproduce if deploying the project from context menu or Command Palette.

**Comment by v-xinda** [comment]
Verified this issue on the latest main branch build 20230420.1, it still reproduces now.

**Comment by alexweininger** [comment]
The error is caused by the tree data provider not bring present on the created web app item. This throws an error when it is refreshed inside of deploy.

It's undefined when the primary item of the create command is a `ResourceGroupsItem`, which doesn't (and shouldn't) have  the `treeDataProvider` property.

So this only reproduces when the entry point to create is  Right clicking the subscription, or App Service grouping items.
