### ISSUE TITLE
Remove repetitive actions when deploying

### ISSUE THREAD

**Issue by bowdenk7** [Microsoft/vscode-azureappservice#284]
Perhaps I'm mistaken, but I remember there being a right click context menu item to deploy (it might've been both zip and git deploy actually), but now it's gone in favor of the new deploy button.

![image](https://user-images.githubusercontent.com/820883/35584244-4e61a47c-05a9-11e8-93a1-f13cafb8fad9.png)

It took me an embarrassingly long time to figure out what changed, and I couldn't figure out how to redeploy my app until I came and read the docs. Even once I found it, clicking deploy forces you to go pick a bunch of options which could be seeded for the user if the deploy is executed through the context menu.

**Comment by EricJizbaMSFT** [comment]
First I'll give a little background on why we made that decision. The most intuitive entry point for deploy is to right click a folder:
![screen shot 2018-01-31 at 9 06 16 am](https://user-images.githubusercontent.com/11282622/35636485-1d3e8398-0666-11e8-816d-aab8a1eb1f42.png)
This experience is common in other tools and IDEs like VS where you right click on a project and deploy. However, there's a few problems with that in VS Code:
1. There's no way to deploy the root of a repo (AFAIK, there's just no api to add a context menu command in that location)
1. Right click menus aren't that discoverable

The old deploy entry point fixed our first issue since you can select a folder. However, it didn't really help the second issue. It was just another context menu command and it was confusing (after all, you're deploying the folder in the screenshot above. What would you be deploying in this case? The app service? That makes me think I'm deploying a _new_ app service in Azure that somehow has the same information as the current app service)

That's why we ended up with the deploy button. It allows the user to deploy the root of the repo and it's more discoverable (at least for new users - sorry it took so long for you to figure out the change 😂).

That being said - I completely agree we should fix the problem you mentioned (having to select the subscription/appservice each time you deploy). Here's my suggestion: what if we had a vscode setting like this:
```
"appService.defaultSubscription": "00000000-0000-0000-0000-000000000000",
"appService.defaultAppService": "exampleAppServiceName"
```

The user could obviously set these at the user or workspace level. I also think it makes sense for these to apply to all app service commands, but I'd be open to deploy-specific settings. For example, if I run 'Create New Web App' from the command palette, we could use the defaultSubscription:
![screen shot 2018-01-31 at 9 33 21 am](https://user-images.githubusercontent.com/11282622/35637789-22325ca4-066a-11e8-95ec-98af97858293.png)

We could even prompt the user after they deploy the first time with something like "Do you want to make this app service the default for this workspace?" with "Yes", "No, Don't Ask Again", and "No" as options

**Comment by fiveisprime** [comment]
I like the idea of allowing defaults and prompting to set the default on deploy.

**Comment by bowdenk7** [comment]
Makes sense. I think my only remaining reservation is that I can't reason about what is going to happen when I click "Deploy to Web App". Now that I know what it does, it is great, but on initial inspection I don't know that it is going to prompt me for additional input.

In the previous UI, by acting on a specific App Service, I knew I was about to zip deploy and I knew exactly where it was going and what was getting demolished. That was great because the first time I downloaded the extension, I was able to confidently deploy without reading any docs. 

In this case, I know I'm about to do a destructive command, I just don't know what the target of that command is. I certainly wouldn't click that button without knowing exactly what it's going to do. For me, that makes finding and reading the docs a pre-req to using the extension (which honestly I'm not sure if that's a good or bad thing). 

Perhaps rewording the tool tip could clear up that it is a command entry point and not an immediately executing event? Perhaps "Deploy to an App Service", "Start an App Deployment", or "App Deploy Wizard" or something of the sort. Just a thought.

**Comment by bowdenk7** [comment]
Definitely +1 on the default subscription/app service settings!

**Comment by fiveisprime** [comment]
Feedback: when presenting the workflow at MVP Summit, I was asked why there's no "right-click deploy" and every person in the room agreed this should be there.

I also received feedback that every command should be in the command pallet: "the first thing I do is open the command pallet and search for the extension to see what's included."

I'm thinking we should add the right-click deploy option back and leave the generic deploy that shows up in the command pallet. I also still *really* like the idea of supporting defaults.

**Comment by EricJizbaMSFT** [comment]
I'm okay adding the right-click deploy back since we've gotten so much feedback to that effect, but I want to emphasize that I would like to keep the current deploy button in the title bar. Its definitely more discoverable and IMO still makes more sense

**Comment by fiveisprime** [comment]
Agreed, sorry if my language was unclear. I'm not proposing we remove the button. 👍
