### ISSUE TITLE
The text box is visible after clicking any one node 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#298]
Repro Steps:

1. Right click one subscription and select 'Create New Web App' then select one subscription.
2. Make sure the text box is displayed to enter a globally unique name for the new Web App.
3. Right click one node and make sure the context menu are displayed.
4. Check whether the text box disappears or not.

Expect:
The text box disappears.

Actual:
The text box doesn't disappear for Azure App Service extension like below. 
![actual](https://user-images.githubusercontent.com/34729092/35966984-64c26f34-0cb7-11e8-9465-d3ed53c750b7.png)

More Info:
The text box disappears for Azure Storage Extension.

**Comment by EricJizbaMSFT** [comment]
@v-dantch This behavior is by design. Since the user has to go through several menus one-by-one in VS Code, it would be annoying if a stray click made you lose all your progress

We've actually had a few issues to this effect:
https://github.com/Microsoft/vscode-azureappservice/issues/42
https://github.com/Microsoft/vscode-azurefunctions/issues/154
