### ISSUE TITLE
A lot of people are cancelling deployment at the "are you sure" step

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azureappservice#348]
Is this indicative of a usability issue?

![image](https://user-images.githubusercontent.com/6913354/37372812-5ee23ade-26d1-11e8-8699-4547637ba789.png)

To a slot:
![image](https://user-images.githubusercontent.com/6913354/37373178-ccdbcbb2-26d2-11e8-8731-2383cdf2bdc6.png)

**Comment by fiveisprime** [comment]
I really think the **"this cannot be undone"** part is what makes this seem so damning. This is descriptive enough without the negative undertone:

>Are you sure you want to deploy to ""? This will overwrite your previous deployment.

I'm thinking that removing the browser launch and the prompt when deploying to a fresh app will help reduce the cancels.

**Comment by EricJizbaMSFT** [comment]
I think we should be careful with this message since we've had a few users accidentally delete their deployment and that's a very frustrating thing (although I think they might've created functions in the portal that got deleted - I'm not sure if this is as relevant for app service)

I'm very undecided on this issue, but I wanted to give a few thoughts:
1. Are we sure a high cancellation rate is a bad thing? Or does it just imply that we have an effective message? After all, the higher the cancellation rate, the lower the rate of accidental deletion of previous deployments
1. We could show a "Learn more" button that opens a page to some custom documentation on deployment methods
1. We could show a "Change deployment source" button

**Comment by fiveisprime** [comment]
I hear you.

1. The high cancel rate indicates _something_. After watching a couple of people deploy using the extension, I hypothesize that people get distracted/confused (browser launch, prompt for deployment changes) and cancel when they eventually make it back to the editor.
2. Fantastic idea. :)
3. It's worth testing, I think something like "deploy to a slot instead" may make more sense.

Based on number 1, I say we let this sit until the end of April and see what the trend looks like. We will have dpeloyed a couple of changes that should reduce the distratcions. Do we have data on how many cancels were on fresh deploys vs. existing deploys?

**Comment by nturinski** [comment]
Somebody was very distratced while drafting this comment apparently.

It depends on what the entry point was for a fresh deploy.  There are two ways to do that today.

1.) You create a new web app through the '+' button, and it prompts the user to deploy upon creation.
2.) You hit the 'Deploy' button, and rather than selecting an existing web app, the user creates a new web app.

I don't think we have those numbers on 1, but that shouldn't be difficult to add and 2 won't be cancelable after this PR https://github.com/Microsoft/vscode-azureappservice/pull/361 is merged.

**Comment by StephenWeatherford** [comment]
FWIW, according to telemetry for last couple of weeks:
1) This step was the source of cancelling the wizard 92% of the time
2) From the people that canceled at this step, 42% went all the way through the wizard for the same webapp within 1/10 of an hour, 60% within one hour, 64% within 24 hours.  

I don't know how many of those changed the slot they were deploying to, but I could find out.

**Comment by fiveisprime** [comment]
What does the current dataset say about cancellations?

**Comment by StephenWeatherford** [comment]
![image](https://user-images.githubusercontent.com/6913354/40570297-2682108c-603e-11e8-8b37-2388827bad64.png)

![image](https://user-images.githubusercontent.com/6913354/40570330-835ef338-603e-11e8-8b66-a4188c17bf19.png)

From the people that canceled at this step, 53% went all the way through the wizard for the same webapp within 1/10 of an hour, 70% within one hour, 77% within 24 hours.

**Comment by StephenWeatherford** [comment]
Agree

**Comment by fiveisprime** [comment]
Safe to close
