### ISSUE TITLE
Deploying .NET Core WebApp Should Run Publish First

### ISSUE THREAD

**Issue by sunmorgus** [Microsoft/vscode-azureappservice#389]
When deploying a .net core WebApp, the extension should fist run a `dotnet publish` command and use the default location of `bin/Debug/netcoreapp2.0/publish` directory as the directory to deploy. Currently, it deploys the working directory, which does not result in a working WebApp.

Perhaps this could be implemented with a "pre-deploy" command in the settings? Will investigate over the weekend.

**Comment by EricJizbaMSFT** [comment]
I actually worked on [something similar](https://github.com/Microsoft/vscode-azurefunctions/issues/223) in the functions extension recently. Rather than a "pre-deploy" command setting, I chose to look for a 'publish' task in your 'tasks.json' file and just run that before every deploy. That being said, I had to depend on an experimental api in VS Code that won't be generally available for at least a month. See [here](https://github.com/Microsoft/vscode/issues/45664) for more info, but it basically provides a way to list and run tasks from an extension.

Feel free to investigate, but right now waiting for that API seems like the best option. I think  VS Code's task system has a lot of benefits and I would prefer to leverage that if at all possible. I definitely don't want to end up re-implementing our own custom task system.

That being said, you (or we) could certainly fix the other issue by adding some sort of user setting for the default path. We actually have a 'deploySubPath' setting in the functions extension that does exactly what you want - if that works for you, you could just use the same pattern https://github.com/Microsoft/vscode-azurefunctions/blob/master/package.json#L539

**Comment by sunmorgus** [comment]
Yeah, I agree waiting for that API seems like the best way to go... no sense in re-inventing the wheel lol.

I'll take a look at the 'deploySubPath' setting and get something submitted for review :)

**Comment by JeroenVogelpoel** [comment]
Is there any progress on this issue yet?

Out-of-the-box deployments of ASP.Net Core projects to Azure App Services using this VS Code extension still results in faulty deployments using the wrong artifacts. The API referenced should/would/might be available now?

Also, there seems to be no implicit publish action at all when deploying; just a regular Debug build being copied over to App Services.

**Comment by EricJizbaMSFT** [comment]
Yeah that api is ready - I'll stick this in the current milestone
