### ISSUE TITLE
Remote debugging telemetry

### ISSUE THREAD

**Issue by mrcrane** [Microsoft/vscode-azureappservice#417]
Add some telemetry to remote debugging actions so that we can track usage, errors, and latency.

**Comment by EricJizbaMSFT** [comment]
FYI a lot of this is included by default because you use `actionHandler.registerCommand` [here](https://github.com/Microsoft/vscode-azureappservice/blob/master/src/extension.ts#L331). Under the covers that calls [callWithTelemetryAndErrorHandling](https://github.com/Microsoft/vscode-azuretools/blob/master/ui/src/callWithTelemetryAndErrorHandling.ts), which can also be called by itself if you want to add more custom telemetry. See [here](https://github.com/Microsoft/vscode-azuretools/tree/master/ui#azure-action-handler) for more info on the actionHandler.
