### ISSUE TITLE
Rename "Attach debugger" action to "start remote debugging

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-azureappservice#420]
Our customers expect "remote debugging on azure", so I'd like us to rename "Attach debugger" action to "start remote debugging", which is more explanatory, and precise than "attach debugger"

**Comment by EricJizbaMSFT** [comment]
So I actually thought about this quite a bit when the Java team was adding remote debug support in the Functions extension. I think either option would be okay, but I have a preference for "Attach debugger" for the follow reasons:

1. 'attach' implies I'm debugging something that already exists while 'start' implies I'm debugging something that will be spun up fresh
1. 'remote' and 'on azure' feels implied since I'm right-clicking a web app
1. "Attach Debugger" is an established pattern:
    1. [Web App in VS](https://blogs.msdn.microsoft.com/benjaminperkins/2016/09/22/remote-debug-your-azure-app-service-web-app/)
    1. [Generic node app in VS Code](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging) (There's no right-click menu in this case, but they still call it 'Attach to remote' in the launch.json)
    1. [Service fabric in VS](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-debugging-your-application#debug-a-remote-service-fabric-application)
    1. [Cloud service in VS](https://docs.microsoft.com/en-us/azure/vs-azure-tools-debug-cloud-services-virtual-machines#to-attach-the-debugger-to-a-cloud-service-in-azure)
1. I like that 'Attach Debugger' is sufficiently different than the other two commands
![screen shot 2018-04-25 at 10 48 25 am](https://user-images.githubusercontent.com/11282622/39263164-40294b2a-4876-11e8-9fcb-1da9e89b00db.png)

**Comment by auchenberg** [comment]
Attach implies that we don't do additional work when running the action, and that's not true. We run a series of actions that could enable remote debugging on the fly, followed by attaching the debugger. That has to be reflected in the naming.

We shouldn't look to VS as our guideline but what's a more non-IDE and simpler approach which is reflected in the VS Code experience. Our VS Code users don't understand the differences between attach/launch abd it's a general feedback item. We should aim to shield users from the technical detail and here we have the opportunity. Using "start" wording would be sufficient abstraction.

My suggestion is that we simpify the experience to two actions:
- Start remote debugging which will enable remote debugging and attach
- Disable remote debugging which will disable as a extra manual action if our users disregard the prompt we added when stopping debugging.

We should also remove the "enable remote debugging" action as it has no real functionality as it's already included in the start action.

@mrcrane @ericJizbaMSFT

**Comment by mrcrane** [comment]
I conceptualize the commands as three distinct actions. If the user tried to attach a debugger without debugging enabled, the simplest implementation would be to not allow it. Instead, we're nicer about that and ask the user if they would like to run the enable command first. If remote debugging is already enabled, we perform the attach command only. I like the symmetry of Enable/Disable with the additional Attach command.

However, I see your point that it's a bit confusing and there's no real need for a user to Enable if we have included it as an option in Attach. If we remove it though, I think having a standalone Disable is also a bit confusing. It's included for a smaller case that is somewhat technical and not immediately obvious. If the goal is simplicity, maybe we're better off with just one command?

Is there any way we can make this decision with data?

My gut says "Start Remote Debugging" is a little vague. Maybe "Start Remote Debug Session" would be more accurate. I don't feel too strongly about this.

As I'm typing this I'm thinking it would be nice to have mouseover documentation or some other easily discoverable documentation for these commands so that they can learn more. Just a thought.

**Comment by EricJizbaMSFT** [comment]
Yeah I think remote debugging is an advanced scenario and the wording will be confusing to some people no matter what is picked. I still think "attach" is better because it's the established pattern in VS _and_ VS Code, but I'm fine using this extension as an "experiment" to try other wording.

I could go either way on "enable remote debugging" as well. We could argue that it's less about functionality and more about discoverability/education (aka it makes clear that remote debugging requires changes to your Azure App). On the other hand, I'm a fan of reducing the number of commands in a context menu and we could argue that the prompt included in attach/start already conveys the info needed.

**Comment by mrcrane** [comment]
I like the discussion here, but also it would be nice to get a PR in soon so that we are ready for the first release of this feature sometime next week. Obviously we can change it easily in the future. I'm happy to go along with whatever @auchenberg decides at this point.

**Comment by EricJizbaMSFT** [comment]
Fine with me

**Comment by fiveisprime** [comment]
Agreed on going ahead with "Start remote debugging" then test and iterate.

"Enable", "Disable", and "Attach" make the most sense to me, but I'm far more interested in what our customers think. I'll work with @auchenberg to communicate with the customers that are currently lined up to use this feature as well as the customers that I regularly talk with to get some more feedback once it's launched and we can show it to them. This kind of feedback is pretty typical when asking somebody to step through a process.

>Is there any way we can make this decision with data?

This question is key. 😃 I believe we can and it requires having something to show so let's get something in people's hands, let them try it, and see if they get stuck at all.
