### ISSUE TITLE
Display incorrect order for the generated file name after clicking 'Generate Azure CLI Script' several times for one web app

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azureappservice#446]
Repro Steps:
1. Right click one web app and select 'Generate Azure CLI Script'.
2. Check the opened file name.
3. For the same web app, click 'Generate Azure CLI Script' several times.
4. Check the file name again.

Expect:
It displays correct order for the generated file name like 'Untitled-1' -> 'Untitled-2' -> 'Untitled-3' -> 'Untitled-4' -> 'Untitled-5'.

Actual:
Display incorrect order for the file name: 'Untitled-1' -> 'Untitled-2' -> 'Untitled-3' -> 'Untitled-2' -> 'Untitled-3'…

**Comment by nturinski** [comment]
This might be non-trivial to resolve.  VS Code uses this external library for creating documents.
`import { ExtHostDocuments } from 'vs/workbench/api/node/extHostDocuments';`

Seems like however this is being created, there's a bug that doesn't keep track of all the untitled documents.  So after 1, it alternates between Untitled 2 and Untitled 3 indefinitely.  I'm not sure there's anything we can do on our end since all we relying on vscode commands to create/show the document via the following:

`const doc = await vscode.workspace.openTextDocument({ language: 'shellscript', content: script });`
`await vscode.window.showTextDocument(doc);`

**Comment by EricJizbaMSFT** [comment]
Since this is handled directly by VS Code and is low priority, closing as won't-fix
