### ISSUE TITLE
Start remote debug fails with timeout

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#448]
It seems this issue (https://github.com/Microsoft/vscode-azureappservice/issues/435) might not be fully solved based on recent telemetry. About half of users are failing with error "Unable to establish connection to application after 30000 milliseconds"

**Comment by mrcrane** [comment]
This error occurs when a tunnel cannot be established with the Azure instance.

As a recap, this process follows these steps:
1. Set the app config remoteDebuggingEnabled=true
2. This triggers an app restart which should* automatically launch the node process in "inspect" mode and configure the tunnel to connect to the inspect port.
3. The extension polls the tunnel status API for up to 30 seconds to determine if the app has finished rebooting and the tunnel is ready.
4. When the tunnel status API says it is ready, the tunnel proxy is established.
5. The debugger attaches to the process through the tunnel proxy.

The error indicates that we are timing out on step 3. It is possible that the app is taking longer than 30 seconds to reboot, or that the node process was not launched in "inspect" mode properly, or that the tunnel was otherwise not configured by Azure properly.

We would need visibility into Azure to know exactly what's happening, but that would be difficult to correlate with the extension telemetry.

My assumption is that in a significant number of these scenarios, the node process is not being launched in inspect mode. This is a known issue for apps that have start commands configured in package.json, which is a common scenario. The App Service team has a fix for this which is not deployed yet. @rramachand21 would have more context on that.

**Comment by mrcrane** [comment]
We have made several improvements since this issue was created. Primarily, we integrated with a new Kudu API that gives us a status of the app and can give insight into whether the app has restarted or not. The timeouts should be greatly reduced now, and most failures should be showing a more specific error message.
