### ISSUE TITLE
Plan pricing tier should have a description

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azureappservice#54]
Just thought it might be nice to include something like "1 Core, 1.75 GB RAM" in each pricing tier description. By itself, 'S1' and 'Standard' doesn't mean much to me

**Comment by fiveisprime** [comment]
Agreed. We should also default to B1 now that there's a 30 day free trial for those.

Sizing is the same for both basic and standard, the difference is in some features (slots, autoscale, backups, traffic manager) and basic is marked as "dev/test."

B1 - 1x Core 1.75 GB
B2 - 2x Cores 3.5 GB
B3 - 4x Cores 7 GB

S1 - 1x Core 1.75 GB
S2 - 2x Cores 3.5 GB
S3 - 4x Cores 7 GB

It would be nice to somehow explain that this infra can be shared for many apps. Maybe that will become a non-issue once we start defaulting on creation.

**Comment by nturinski** [comment]
I don't see cores being listed in the portal anymore, but there are GB size and ACU (Azure Compute Units).  ACU is a very specific vernacular that I'm not sure we want to show.

![image](https://user-images.githubusercontent.com/5290572/60472623-65a86f00-9c1e-11e9-8a55-aaba1380501e.png)

**Comment by fiveisprime** [comment]
Add a selection in the quick pick that says "Show pricing calculator..." and send them to https://azure.microsoft.com/en-us/pricing/calculator/

**Comment by fiveisprime** [comment]
Would the information in this link be a better fit for this?

https://azure.microsoft.com/en-us/pricing/details/app-service/linux/

**Comment by wwlorey** [comment]
I think it would. The original pricing calculator link requires a few steps to show the info. Would we update the "Show pricing calculator..." link text as well?

**Comment by nturinski** [comment]
@fiveisprime  Also, each page is specific to the resource that you are creating.  For example, there are also
https://azure.microsoft.com/en-us/pricing/details/cosmos-db/
https://azure.microsoft.com/en-us/pricing/details/functions/
https://azure.microsoft.com/en-us/pricing/details/storage/

Because the ASPs are handled by the shared package, this link would be exposed in any extension that uses App Service Plans.  So we would have to check which extension is calling the App Service Plan step before creating the link which is quite a bit of extra work.

I do think that these pages are better and more straight forward though, but not sure about the extra engineering work involved for it.

**Comment by EricJizbaMSFT** [comment]
If the user got to the `AppServicePlanListStep` in Functions, that means they explicitly selected "App Service Plan" in [this step](https://github.com/microsoft/vscode-azuretools/blob/master/appservice/src/createAppService/SiteHostingPlanStep.ts#L17), which means the app-service link _will_ be appropriate in that scenario. Sounds like all you would have to account for is the different OS's and that seems pretty reasonable.

**Comment by nturinski** [comment]
What about consumption plans?  The user can pick between the two in Functions, right?

**Comment by EricJizbaMSFT** [comment]
Take a closer look at the step I linked: https://github.com/microsoft/vscode-azuretools/blob/master/appservice/src/createAppService/SiteHostingPlanStep.ts#L17

Consumption plans lead down a separate path in the wizard

**Comment by fiveisprime** [comment]
Fair enough, leave the pricing calculator for now and we can revisit this if we need to.
