### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by charlix216** [Microsoft/vscode-azureappservice#541]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.9.0
OS: darwin

**Comment by nturinski** [comment]
Hi @charlix216,

Thanks for reporting this issue.  I'm sorry that you haven't been able to deploy.  Could you give me some more information so that I could begin investigating your issue?

1. What OS and runtime is your web app?
1. What type of App Service Plan are you on?
1. What kind of project are you trying to deploy?

**Comment by charlix216** [comment]
Thank you for reaching out . I’m running on Mac OS . I’m on pay as you go plan and I was trying to deploy an angular 2 app. The problem seems to be fixed and haven’t had problems.
