### ISSUE TITLE
github repositories don't show all repos

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-azureappservice#557]
Wanted to show you the experience i had today with this ... notice that I have a lot of repos. it took me a few times "load more" to get the one i wanted to show. the sequence seemed odd too ... alpha or most recently used would be nice. also, i expected auto-complete to work without having to "load more" (which wasnt obvious till i scrolled to the bottom.

Asks:
1. sort the repos in most recently used or alphabetically
2. if "load more" is needed, make it more obvious (maybe at the top?)
3. instead of load more, show all repos
4. allow type ahead to find a repo, even if it's not shown in the dropdown

See this video below ...

https://www.dropbox.com/s/n7kz48jdhuw1bbq/github%20deploy.mp4?dl=0

**Comment by EricJizbaMSFT** [comment]
Similar to https://github.com/Microsoft/vscode-azurefunctions/issues/455 in functions

**Comment by EricJizbaMSFT** [comment]
@nturinski improved this behavior in PR https://github.com/Microsoft/vscode-azuretools/pull/310, but I think there's a few things we have to do before closing this:
1. Show progress in quick pick when loading repos (Just need to pass a Promise of an array instead of an array to `showQuickPick`)
1. Move "Load more" to the top to make it more obvious
1. Sort projects alphabetically

@nturinski I think this needs to be done before releasing 0.10.0
