### ISSUE TITLE
Connecting AppSevice web apps to CosmosDB

### ISSUE THREAD

**Issue by jinglouMSFT** [Microsoft/vscode-azureappservice#568]
Target scenario for MVP: Connecting a CosmosDB account includes any of the CosmosDB APIs along with external connections. It's important to note that the connection needs to be as open as possible with the database connection to enable users to choose a service other than CosmosDB. However, if the user already has the CosmosDB extension installed and is connected to external accounts, we should include it in the connection selection.  Some early thoughts:

1. Expand Connected Experience (a place hold name) node then expand CosmosDB node
2. When no accounts are connected, only the option to connect is present "Connect CosmosDB Account"
3. Clicking the message begins the connection process
    - If the user doesn't have the CosmosDB extension installed, they are prompted to install it
    - If they do, the account selection quick-pick opens to show existing accounts
4. User chooses account and database
5. The connection string for the CosmosDB account/database is configured as an app setting for the Web App

Once services are connected, there are some other help we can provide. For example:
- Picking the correct SDK module
- Scaffolding authentication code for the SDK if necessary
- Scaffolding common code (e.g. connecting to a Mongo DB using the connection string, etc)

**Comment by EricJizbaMSFT** [comment]
I've created the first three 'features' based off of this. Each feature isn't necessarily helpful by itself, but I think that's fine since the whole thing will be under a feature flag. I was just trying to split the work up into smaller pieces. Here they are, in order:
https://github.com/Microsoft/vscode-azureappservice/issues/582
https://github.com/Microsoft/vscode-azureappservice/issues/583
https://github.com/Microsoft/vscode-azureappservice/issues/584
