### ISSUE TITLE
Miss 'select a location step' when creating  a new web app with false 'appService.advancedCreation' setting

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azureappservice#596]
Repro steps:
1. Open App Service Extension.
2. Go to File-> Preferences-> Settings-> Set 'appService.advancedCreation’:true.
3. Click '+' to cretae a new web app.
4. Respond with a valiad name , then check whether prompt to select a location or not.

Expect:
After entering a valid name, prompt to select a location.
 
Actual:
After entering a valid name, prompt to select an OS directly not location.

**Comment by EricJizbaMSFT** [comment]
So we actually don't display the location in most cases - by design.

First of all, we don't display it if `advancedCreation` is `false`. This is a recent change - see https://github.com/Microsoft/vscode-azureappservice/issues/536

Secondly, we don't display it if you select an existing App Service Plan even if `advancedCreation` is `true`. This is because the performance is better if the plan and the app are in the same location (so we just use the plan's location when creating the app). The portal does the same thing here:
![screen shot 2018-08-31 at 8 54 37 am](https://user-images.githubusercontent.com/11282622/44922917-93b9db80-acfb-11e8-9315-ac4be660f950.png)

The only time you will be prompted for location is if you have `advancedCreation` as `true` and you're creating a new plan. In which case, the location prompt is the very last prompt. This is still working when I just tested it out.
