### ISSUE TITLE
Support using Free tier Web Apps

### ISSUE THREAD

**Issue by milkshakespoon** [Microsoft/vscode-azureappservice#608]
I use an account where I deploy web apps for free using the Free Tier. 

Is it possible to add this as a deployment option when picking which size instance?

**Comment by EricJizbaMSFT** [comment]
A few things about this:
1. Are you using a windows or linux App Service Plan? I believe free is only supported on Windows
1. We use "Free" for windows plans when "appService.advancedCreation" is set to false (the default)
1. If you have "appService.advancedCreation" set to true, you should be prompted to set the sku like this:
![screen shot 2018-09-10 at 9 36 07 am](https://user-images.githubusercontent.com/11282622/45311340-a68f9580-b4dd-11e8-9b6d-3ec00bcf8e9d.png)

I see "Free" listed there. We released an update just last Friday and I believe that might've been the first release to have it - so just make sure you're up to date (v0.9.1). Closing this as fixed in https://github.com/Microsoft/vscode-azuretools/pull/226, but feel free to re-open if you're talking about something else
