### ISSUE TITLE
publish web app to azure app service failed

### ISSUE THREAD

**Issue by jakeren** [Microsoft/vscode-azureappservice#770]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: EPIPE
Error Message: write EPIPE

Version: 0.10.0
OS: darwin

**Comment by nturinski** [comment]
Hi @jakeren,

I'm sorry that you are having issues with deploying.  Has this issue been reproducible?  An EPIPE error happens when one end of the connection is closed.  Maybe there was an outage at the time you tried to deploy?  If this is not the case, could you answer the following question?

1. Was this a new web app?
1. Is this a Linux or Windows app?
1. What type of project are you trying to deploy?

Thank you!
