### ISSUE TITLE
Deleting several app service instances in a row results in error about acquiring lock

### ISSUE THREAD

**Issue by nnja** [Microsoft/vscode-azureappservice#781]
Repro steps:
Enter steps to reproduce issue:
I deleted 5 or 6 instances in a row by right clicking and selecting delete. One of the deletes failed with the error message below.

Action: appService.Delete
Error type: 429
Error Message: Cannot acquire exclusive lock to create, update or delete this site. Retry the request later.

Version: 0.10.0
OS: darwin

**Comment by nturinski** [comment]
Hi @nnja, Thanks for reporting!

I think that there's a request limit on the Portal's end.  A [429 status code](https://httpstatuses.com/429) seems to indicate that there were "Too Many Requests".  Does this error persist?

**Comment by nnja** [comment]
It did not, I was able to delete the resource after the error popped up. 

It is possible to bump up that limit, limit concurrent requests, or possibly prevent hitting that limit from the extension? I was only modifying a handful of resources.

**Comment by EricJizbaMSFT** [comment]
Sorry for the delayed response - in regards to a few of your suggestions:

> bump up that limit

We don't set this limit - the error is coming directly from Azure.

> limit concurrent requests, or possibly prevent hitting that limit from the extension?

This is potentially possible, but I'm hesitant to add hard-coded limits to our extension when this could be caused by multiple factors:
1. Internet speed
1. App Service plan size
1. Number of sites on a single plan
1. Azure outage status

I'm going to close this as won't fix since you were able to delete this resource and I haven't heard of many people hitting this. I tried deleting 6 apps at the same time and didn't hit the error. Thanks for filing the issue and let us know if you strongly disagree with the prioritization
