### ISSUE TITLE
Ping/wake site prior to attempting to connect remote debugging/SSH session

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#801]
If an app has gone to sleep, the first attempt to connect to the SSH tunnel will fail. The extension should ping to wake before attempting to connect (similar to how log streaming wakes).

//cc @mrcrane

**Comment by mrcrane** [comment]
See microsoft/vscode-azuretools#514 for a discussion about stopped apps vs. sleeping apps

The change in the PR will make it so that stopped apps will be started automatically and sleeping apps will be woken up automatically when remote debugging is started. We can, however, use SiteClient.getState() to differentiate between the two cases.

@fiveisprime can you comment on what you would like the experience to be if the user has explicitly stopped the app? Should we start the app silently or prompt the user?

If we prompt the user, imagine that the user also needs to enable remote debugging. We might get 2 prompts in that case: "Your app is stopped, do you want to start it?" -> clicks yes -> "Remote debugging is disabled, do you want to enable it?" -> clicks yes -> debugging starts.

Maybe we could have one dialog that says something generic like "Do you want to enable remote debugging and restart the app?" which would cover consent to do both at the same time?

**Comment by fiveisprime** [comment]
Either a single message to start and update or just fail with a message that the app needs to be running.

Definitely don't want to see two prompts.

**Comment by nturinski** [comment]
This was fixed by here @mrcrane https://github.com/microsoft/vscode-azuretools/pull/522 and here https://github.com/microsoft/vscode-azuretools/pull/514
