### ISSUE TITLE
Smart defaults for Java apps

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-azureappservice#848]
For Java apps, the recommended defaults are:
- OS: Linux
- Plan: P1V2

Java apps can be identified by some indicators:
Maven - pom.xml
Gradle - build.gradle

So while deploying Java apps, we only need to ask the users for a name and a runtime of their app.

**Comment by jdneo** [comment]
@EricJizbaMSFT Just to double confirm that: Is the `smart defaults` here means the `advancedCreation` in the extension setting?

If `advancedCreation` is enabled, then the extension will detect the project type and use the recommended values as default?

**Comment by EricJizbaMSFT** [comment]
I think you have it backwards. If `advancedCreation` is on, we prompt them for basically everything, including OS and plan. The recommendations above have no effect.

If `advancedCreation` is _not_ on (the default), we will try to figure out what type of project they have and use the smart defaults above and will _not_ prompt for the OS or plan.

We call it "smart" defaults because the extension is being "smart" for the new user and picking what should work for them. We call it "advanced" creation because advanced users might know better for their specific situation than we do and want to explicitly choose things like OS and plan.

**Comment by jdneo** [comment]
@EricJizbaMSFT Thank you for the explanation. I got your points now.
