### ISSUE TITLE
App Service Deployment Fails - "Central Directory corrupt"

### ISSUE THREAD

**Issue by mike-marshall** [Microsoft/vscode-azureappservice#867]
I've got a node.js app written in VSCode, and I'm trying to deploy it to an Azure Web app:

Reproduction steps:

Local environment:

Windows 7
VS Code 1.31.0
Azure App Service extension: v0.12.0

1. Create node app with "express-generator" npm package
2. Test locally - works fine
3. In app service extension sidebar, click "Deploy Web App..."
4. Name Web App ("mywebapp123")
5. Select Linux OS (LTS version)
6. Wait for deploy

Output log in VSCode:

> Error: Deployment to "mywebapp123" failed. See output channel for more details.
4:05:47 PM mywebapp123: Creating zip package...
4:06:03 PM mywebapp123: Starting deployment...
4:07:42 PM mywebapp123: Fetching changes.
4:07:42 PM mywebapp123: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/s2tvr0o6.zip (0.00 MB) to /tmp/zipdeploy/extracted
4:07:42 PM mywebapp123: Central Directory corrupt.
Error: Deployment to "mywebapp123" failed. See output channel for more details.

**Notes:**

- Notice the zip file on the server is said to be 0.00 MB.  Local Windows temp file show it is ~6 MB
- Zip file name on server (s2tvr0o6.zip) does not match local windows temp zip file name
- I'm behind a corporate proxy, not sure if this may be impacting zip upload?

**Comment by EricJizbaMSFT** [comment]
@mike-marshall the zip file on the server won't match the local name, that's expected. However, the size should match. How are you checking the temp file? Just based on timestamps?

How are you deploying? We have several entry points, including:
1. Right click on a folder
1. Right click on a web app
1. Blue up arrow in App Service explorer
1. Command Palette

The reason I ask is because if you're using the first entry point, we deploy the exact folder you click on (as opposed to the whole workspace), which may be empty. Unless you have `appService.deploySubpath` set? If you use that setting, we will always deploy the same subfolder no matter the entry point.

Finally - was this a one-time issue or does it happen consistently?

**Comment by mike-marshall** [comment]
To answer you question, I used the blue "up arrow" in the Azure extension sidebar on vscode. Turns out I believe this is corporate firewall related. I tried it on a different network and deployment succeeded. It would be interesting to see if there could be better error handling around zip upload. But since it seems to be related to my network I'm closing

**Comment by EricJizbaMSFT** [comment]
Glad you got it figured out. I'd suggest taking a look at this setting that was recently released in VS Code: https://code.visualstudio.com/updates/v1_31#_network-proxy-support-for-extensions It should be on by default, and hopefully solves a lot of proxy problems (although probably not all)
