### ISSUE TITLE
Cannot deploy due to 'git history diverging'.

### ISSUE THREAD

**Issue by tiloc** [Microsoft/vscode-azureappservice#883]
**Repro steps:**
I am setting up a completely new app service based on Python 3.7. I set LocalGit as my deployment source. I trigger the deployment. At first I am getting a message that I cannot deploy due to "git history diverging". I am asked whether I want to force push. I say yes. Then I get the below error message and the kind offer to open an issue. I have no clue what might be "diverging" here? My local git from a brand new empty remote git??

Action: appService.Deploy
Error type: Error
Error Message: error: Cannot access URL https://$redacted@django-health.scm.azurewebsites.net/, return code 22
fatal: git-http-push failed
error: failed to push some refs to 'https://$redacted@django-health.scm.azurewebsites.net'

Version: 0.12.0
OS: darwin

**Comment by nturinski** [comment]
Hi @tiloc,

Really sorry for this blocking issue.  

The error "git history diverging" is definitely wrong in this case.  When a git push fails, we look for the string "failed to push" because that language is included in a diverging history error, but we make that error actionable with the `Force Push` prompt.  Thanks for reporting this.  It will be fixed soon.

As far as the return 22 code error, I'm looking into this now.  In the meantime, if you need to deploy your application, you can do so via the Git CLI.  If you look at your app on the portal, you'll find your Git Clone Uri under Deployment Center:

![image](https://user-images.githubusercontent.com/5290572/53772948-2dc23280-3e9d-11e9-8cb2-a8c69d1c15c0.png)

If you click Deployment Credentials, you will have the username/password combination.

In the Git CLI, you can `git push gitcloneuri master` and when prompted for authentication, use that un/pw combination.

Incredibly sorry about this error.  We hope to resolve this soon.

**Comment by nturinski** [comment]
@tiloc This should be fixed with the latest release.  Please let me know if that hasn't resolved your issue.
