### ISSUE TITLE
Appsetting issue

### ISSUE THREAD

**Issue by surajsingh290** [Microsoft/vscode-azureappservice#943]
Repro steps:

1.
2.

Action: appService.appSettings.Add
Error type: BadRequest
Error Message: AppSetting with name 'MICROSOFT_BOT_APP_ID=66cc0dcb-c870-4ac1-b901-00b3635de619' is not allowed.

Version: 0.13.0
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
module.exports.E.l.pipeline (dist/extension.bundle.js:277:1449893)
s (dist/extension.bundle.js:277:112563)
s (dist/extension.bundle.js:165:26036)
dist/extension.bundle.js:165:27276
o (dist/extension.bundle.js:223:7054)
dist/extension.bundle.js:165:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:521656)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (int

**Comment by nturinski** [comment]
Hi @surajsingh290 

Seems like your key value isn't valid due to the `-` in them.  But I believe that you can make the key `MICROSOFT_BOT_APP_ID` and the value `66cc0dcb-c870-4ac1-b901-00b3635de619` like so

![image](https://user-images.githubusercontent.com/5290572/56312255-9e977400-6104-11e9-8b3b-899a02f5817e.png)

But there is a bug that keeps causing the app setting entry to fail if it has failed once (seems like the key is being cached or something) so I will investigate that.

Thanks for reporting!
