### ISSUE TITLE
Web Apps deployment from extension failed

### ISSUE THREAD

**Issue by nnja** [microsoft/vscode-azureappservice#975]
Changed deployment source from LocalGit to None.

After trying to deploy again, I see this error.
There are no further instructions or guidelines for how to fix my issue.

```
Deployment source for "app-name-here" has been updated to "None".
6:32:38 PM app-name-here: Creating zip package...
6:33:00 PM app-name-here: Starting deployment...
6:35:40 PM app-name-here: Fetching changes.
6:35:40 PM app-name-here: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/bf02b21c-3d73-430c-84da-9226771decad.zip (0.00 MB) to /tmp/zipdeploy/extracted
6:35:40 PM app-name-here: Central Directory corrupt.
Error: Deployment to "app-name-here" failed. See output channel for more details.
```

**Comment by nturinski** [comment]
@nnja Have you tried reproducing this on the Azure CLI?  

Since deployment output is coming from Azure, I've never seen this error before, but you could try checking the Files/Logs nodes to see if there are any clues as to what went wrong.

Alternatively, you could use the Deployments node and redeploy the previous commit that hasn't been corrupted.

**Comment by nturinski** [comment]
These issues might be able to assist you:
https://github.com/Microsoft/vscode-azureappservice/issues/415
https://github.com/Microsoft/vscode-azureappservice/issues/867
